title: Tanya Marwah
description:

permalink: /writings/:year/:month/:day/:title/

plugins:
- jekyll-seo-tag

google_analytics: UA-000000-0
github:
  is_project_page: false
  tm_github_url: https://github.com/tm157/
  tm_google_scholar: https://scholar.google.com/citations?hl=en&user=_Y_XvN4AAAAJ
