baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tanya Marwah'
theme = "hugo-blog-awesome"

# Enable emojis globally
enableEmoji = true

[services]
  [services.googleAnalytics]
    id = '' # G-MEASUREMENT_ID (add later)

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

############################## Menu ################################
[menu]
[[menu.main]]
  pageRef = "/"
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef = "posts"
  name = 'Blog'
  url = '/posts/'
  weight = 20

############################## Params ################################
[params]
  sitename = "Tanya Marwah"
  defaultColor = "auto" # dark, light, or auto
  description = "Research Fellow at Simons Foundation"
  goToTop = true
  dateFormat = "2 Jan 2006"
  rssFeedDescription = "summary"

[params.author]
  avatar = "avatar.png"
  intro = "Tanya Marwah"
  name = "Tanya Marwah"
  description = """
I am a Research Fellow at the [Simons Foundation](https://www.simonsfoundation.org/) working with [Polymathic AI](https://polymathic-ai.org/). I recently graduated with a PhD from the Machine Learning Department at Carnegie Mellon University co-advised by [Prof. Andrej Risteski](https://www.andrejristeski.org/) and [Prof. Zachary Lipton](https://www.zacharylipton.com/). Previously, I was a masters student in the Robotics Institute at CMU and was a Siebel Scholar.

I work on the empirical and theoretical foundations of Machine Learning and its applications to scientific domains. My current interests are around generative modeling of scientific phenomena, inverse problems and building scientific agents. My ultimate goal is to develop ML algorithms and methods that help us accelerate the scientific process and enable scientific discovery.
"""

############################## Social Icons ################################
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/tm157/"

[[params.socialIcons]]
  name = "google-scholar"
  url = "https://scholar.google.com/citations?hl=en&user=_Y_XvN4AAAAJ"

[[params.socialIcons]]
  name = "Rss"
  url = "/index.xml"
